### ISSUE TITLE
[Feature request] Add tooltip to torches.

### ISSUE THREAD

**Issue by Kasualix** [Nyphet/torch-hit#16]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
Add tooltip to torches (use tag) about the whole mod feature.
Example tooltip: _"it will ignite the target!"_

**Additional context**
N/A

**Comment by Crystal-Spider** [comment]
It does sound interesting, however I'd prefer to not add this because of the new translations there would need to be and maintain.  
Also many items in Minecraft do not have a tooltip, for example Flint and Steel. I'd prefer to keep a more Vanilla-friendly system. This way it's also easily possible for other mods to add their own customization, e.g. a mod that adds helpful tooltips on items.
