### ISSUE TITLE
Feature request: Detonate TNT, Creeper with torch

### ISSUE THREAD

**Issue by someone5678** [Nyphet/torch-hit#7]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Detonating TNT, Creeper with torch by "mouse right click with torch while pressing down shift key".

E.g. Tree harvester mod makes entire tree instantly break with "Break one log with Axe while pressing  down shift key".
https://modrinth.com/mod/tree-harvester

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Crystal-Spider** [comment]
When I created this mod I left out this functionality on purpose to leave a meaning for Flint and Steel.  
Making torches be able to explode Creepers and TNTs would be a little too much in my opinion.

It kinda would be like having an unbreakable Flint and Steel at that point. Yes, it's true, F&S can also set blocks on fire whereas torches cannot, but then the question is: since torches can set off Creepers and TNTs, why can't they also set blocks on fire?  
My approach to this is to avoid the question entirely by making it impossible to set off Creepers and TNTs with torches.
